name: "Global - CI"

on: [pull_request]

jobs:
  build:
    name: "CI"

    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      - name: "Check formatting"
        run: npx turbo format:check

      - name: "Build"
        run: pnpm build

      - name: "Lint"
        run: pnpm lint

      - name: "Test"
        run: pnpm test
