name: "CLI - Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      #      - name: "Set up pnpm"
      #        uses: pnpm/action-setup@v2
      #        with:
      #          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      - name: "Publish to npm"
        id: npmPublish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Add version tag"
        if: steps.npmPublish.outputs.type != 'none'
        run: |
          git tag v${{ steps.npmPublish.outputs.version }}
          git push origin v${{ steps.npmPublish.outputs.version }}
