name: "CLI - CI"

on: [pull_request]

jobs:
  build:
    name: "${{ matrix.os }}"

    strategy:
      matrix:
        node: ["18"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up Node ${{ matrix.node }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      - name: "Build"
        run: pnpm build

      - name: "Check formatting"
        run: pnpm format:check

      - name: "Lint"
        run: pnpm lint

      - name: "Test"
        run: pnpm test
