name: "CLI - CI"

on: [pull_request]

jobs:
  get-test-files:
    name: "Get e2e test files"

    runs-on: ubuntu-latest

    outputs:
      test-files: ${{ steps.set-test-files.outputs.files }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      # Build is necessary, as the `get-e2e-test-files-array` script returns built files
      - name: "Build"
        working-directory: packages/create-next-stack
        run: npx turbo build

      - name: "Set test files"
        id: set-test-files
        working-directory: packages/create-next-stack
        run: |
          echo "files=$(pnpm --silent get-e2e-test-files-array)" >> $GITHUB_OUTPUT

  build:
    name: "Test - ${{ matrix.test-file.fileName }} - ${{ matrix.os }}"

    needs: get-test-files

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        test-file: ${{ fromJSON(needs.get-test-files.outputs.test-files) }}

    runs-on: ${{ matrix.os }}

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      - name: "Build"
        working-directory: packages/create-next-stack
        run: npx turbo build

      - name: "Run e2e test: ${{ matrix.test-file.fileName }}"
        working-directory: packages/create-next-stack
        run: pnpm e2e:single:ci ${{ matrix.test-file.filePath }}
