name: "Global - Publish"

# Publishes all packages in the monorepo.
# Packages should specify `private: true` in their `package.json` files, if they shouldn't be published.
# This workflow just installs and runs `pnpm publish`. Each package should add build scripts and similar to its `prepack` script in its `package.json` file.

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: "Install dependencies"
        run: pnpm install

      - name: "Publish packages"
        run: pnpm publish -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
